version: '3'

services:
  fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    environment:
      - BACKEND_URL=http://fastapi-server:8000
    ports:
      - "8501:8501"
