version: '3'

services:
  fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
